### ISSUE TITLE
GitPitch template decision 

### ISSUE THREAD

**Issue by soohun-kim** [KAIST-IS521/2018s-presentation-team6#1]
# GitPitch 발표에 사용할 Template 고르기
### 다양한 Template 존재. 아래 링크에서 하나 고르기 혹은 template customizing 
[GitPitch template](https://gitpitch.com/templates)

**Comment by k1rh4** [comment]
몇개를 써봤는데 이미지 추가하기 위해서는 black이나 white 버젼이 좋은것같아요.

심플한게 배경처리나 꾸미기가 편한듯..

**Comment by sunnyeo** [comment]
Black-Binary Template
Black Template
White Template
Beige Template

저도 심플한 쪽으로...

**Comment by soohun-kim** [comment]
저도 black이 가장 낫다고 생각했는데
그럼 일단 Black으로 잠정적 결론을 내리고 GitPitch조작법 숙달하도록 합시다.
이후에 가능하다면 customizing 해보도록 해요
모두 동의하시면 Close하도록 할게요.
@sunnyeo  @k1rh4

**Comment by sunnyeo** [comment]
넹 그럼 black 으로 가시죠

**Comment by k1rh4** [comment]
블랙에디션 위에 배너 gitpitch 있는거 제가 삭제한 걸로 marge 시켜도 될까요?

**Comment by k1rh4** [comment]
그냥 수정하는게 낫겠네요 ㅋ

**Comment by soohun-kim** [comment]
ㅋㅋ넵 블랙으로 확정. 
본 이슈는 닫도록 하겠습니당
