### ISSUE TITLE
Feedback on your presentation

### ISSUE THREAD

**Issue by DaramG** [KAIST-IS521/2018s-presentation-team6#19]
- Presentation Time
  - Total: 9분 20초
  - 박선녀: 2분 27초
  - 김수훈: 2분 10초
  - 이상섭: 3분 10초
- Team comment 
  - 티에이에 대해서 말한 점이 좋음
  - 전체적으로 안정되고 일관된 슬라이드가 매우 좋음. 슬라이드 자체만 보면 최고점을 주고 싶으나, 발표는 그에 미치지 못함 (어필하는 것이 부족)
  - 발표시간 준수 필요
  - 화기애애하고, 협력을 잘 할 것 같은 팀 분위기가 보였음
  - Profile에서 Motto를 넣은 사람과 아닌 사람이 있고, research interest를 발표내용에 포함한 사람과 아닌 사람이 있는데, 이런 부분 통일하면 더 좋을 듯
- 박선녀
  - 좋은 슬라이드. 하지만 쑥스러워 하는 듯한 모습이 발표 내내 보임
- 김수훈
  - 시선처리가 불안정. 그리고 약간 건들건들하는 모습이 발표 내내 보임. 좀 더 자신의 speech에 신뢰감을 주려면 그러한 부분도 고려해야함
  - Research Interest 슬라이드에서 3가지 그림들의 align이 맞으면 좀 더 좋을 듯
- 이상섭
  - 매우 안정적인 발표
  - 지금까지 본인이 해온 것과 본인의 능력, 특징 등을 알아보기 쉽게 나타내고, 발표 또한 잘함. 하지만 시간(3분) 준수가 필요

**Comment by sangkilc** [comment]
@DaramG Thank you for creating this issue. I think you'd better put the presentation time for each member in your summary.
