### ISSUE TITLE
Create a group PGP key

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-presentation-team6#20]
#### PGP key 생성하고 Key ID 공유하기

**Comment by sunnyeo** [comment]
public key 추가했습니다. 
> gpg --keyserver keyserver.ubuntu.com --recv-key `D788DA45`

**Comment by sunnyeo** [comment]
모두 sign한 후에 #21 이랑 같이 issue 닫도록 할게요

**Comment by soohun-kim** [comment]
우리 team key에 서명 완료했습니다!ㅎㅎㅎ
고마워요!

**Comment by k1rh4** [comment]
저도 우리 팀키에 sign 완료 했습니다.

**Comment by sunnyeo** [comment]
모두 서명했으니 이 이슈는 닫도록 하겠습니다.
