### ISSUE TITLE
Sign the group key

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-presentation-team6#21]
#### The group key should be signed by every member in the team.
- group key에 sign하고 댓글달기
- key 정보는 #20 참고

**Comment by sunnyeo** [comment]
sign 했습니다.

**Comment by sunnyeo** [comment]
아직 refresh-keys해도 안뜨네요 ㅜ 
우선 팀원들 키 모두 sign 했습니다. 
각자 pgp key에 group key sign 뜨는지 확인해주세요!

**Comment by k1rh4** [comment]
sign 완료 했습니다.

**Comment by sunnyeo** [comment]
@k1rh4 sign 확인했습니다.

**Comment by sunnyeo** [comment]
local 로는 아직 못받았지만 key server에는 모두 사인된거 확인했습니다.
http://pgp.mit.edu/pks/lookup?op=vindex&search=0x9797368AD788DA45

**Comment by sunnyeo** [comment]
드디어 모두 완료되었습니다 : )
