### ISSUE TITLE
Submit the group key

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-presentation-team6#22]
#### Put the group key into the `KAIST-IS521/2018-Spring/GroupKeys/` directory.
- name convention: `Team-N-<TeamName>.pub`, where `N` is your team number.

**Comment by sunnyeo** [comment]
다 sign한 후에 리더님이 제출하는걸로...

**Comment by soohun-kim** [comment]
사인 완료하고 제출하였습니당~
