### ISSUE TITLE
Design table of contents

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-presentation-team6#23]
#### [activity manual](https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/0314.md#visualization-and-presentation-group-activity) 기반으로 슬라이드 내용 구성하기

To Do List
- Demonstrate what you have done as a team with PGP keys
- A graph of your team member's web of trust

Checklist
- Did students use PGP keys effectively?
- Are slides concise and easy to understand? Are slides well organized?
- Are graphs readable? Are graphs visually attractive?
- Content is accurate and information is presented in a logical order.
- Are there any mistakes? (e.g., spelling errors, missing references)

**Comment by sunnyeo** [comment]
#### 1. 표지
- 제목 : GPG?
- 팀명 및 팀멤버

**Comment by sunnyeo** [comment]
contents 내용 정해지면 `PITCHME.md` 수정합시다

**Comment by sunnyeo** [comment]
- title
(- 목차?)
- group key 정보 및 모두 서명한 내용
- group key graph
- member key 정보
- member graph
- pgp key activity
(- 결론)

**Comment by k1rh4** [comment]
pgp key 그래프는 각자것도 추가하고 전체 그룹 pgp 도 추가하나요?

**Comment by sunnyeo** [comment]
@k1rh4 그룹 pgp는 그래프가 필요 없을거 같긴해요 ㅋㅋㅋ 어처피 3명 사인한거라 그거만 캡쳐해서 넣어도 될듯여

**Comment by k1rh4** [comment]
contents 이미지 만들어서 추가했습니다.
