### ISSUE TITLE
Discuss what we'll do as a team with PGP keys

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-presentation-team6#24]
#### PGP key를 이용할 방법 의견 나누기
- As an example, you may want to demonstrate how you used PGP keys to securely send emails between team members.

**Comment by sunnyeo** [comment]
commit 할때 sign하기

**Comment by sunnyeo** [comment]
각자 branch에서 작업하고 pgp에 merge할때는 commit들 다 sign되어있는지 확인 후 merge 합시다!

**Comment by sunnyeo** [comment]
mail 보내기
- chrome 확장 프로그램 중 FlowCrypt 라는게 있네요.

**Comment by sunnyeo** [comment]
[GPG 관련 SW](https://www.gnupg.org/software/frontends.html)

**Comment by k1rh4** [comment]
굳굳 선녀님이 보내준 메 스샷 캡쳐해서 추가 했습니다.

**Comment by soohun-kim** [comment]
파일 주고받기 추가 완료!
