### ISSUE TITLE
Contents in personal presentation

### ISSUE THREAD

**Issue by soohun-kim** [KAIST-IS521/2018s-presentation-team6#3]
# Needed contents
1) Who am i
2) Visual aids
3) Development environment
-----
\+ Any other interesting materials

**Comment by k1rh4** [comment]
제분량 추가 완료 하고 master와 merge 하였습니다.

**Comment by sunnyeo** [comment]
저도 merge 완료요!

**Comment by soohun-kim** [comment]
넵 모두 확인했습니다!
수고하셨습니다
