### ISSUE TITLE
Draft version presentation

### ISSUE THREAD

**Issue by soohun-kim** [KAIST-IS521/2018s-presentation-team6#4]
### To prepare each member's draft version presentation based on fixed outline

**Comment by soohun-kim** [comment]
fixed outline 은 #3 에서 논의하여 결정한 내용

**Comment by k1rh4** [comment]
outline 페이지 수정하였습니다.
크게는 폰트 크기와 who am i 부분의 색깔이 포인트고,
사진이 존재할시 왼쪽 정렬을 template으로합니다.

**Comment by k1rh4** [comment]
템플릿 형태 전원 일치 확인
