### ISSUE TITLE
outline feedback

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-presentation-team6#42]
commit d20b53895bc2bab75c0927b060dc2342ab6790f0 feedback

**Comment by sunnyeo** [comment]
[3장](https://gitpitch.com/KAIST-IS521/2018s-presentation-team6/onion#/3) 그림 굳굳 좋아여
[4장](https://gitpitch.com/KAIST-IS521/2018s-presentation-team6/onion#/4) 글씨 너무 많은데... 제 생각엔 3장에서 어느정도 설명될거 같은?
[5장](https://gitpitch.com/KAIST-IS521/2018s-presentation-team6/onion#/5) 굳이 넣어야 할까요?

**Comment by sunnyeo** [comment]
implementation 은 각 부분을 설명하려고 하신건가욤?
static analysis는 test에 들어가도 되지 않으려나요?
test도 뭔가 깔끔한 정리가 필요할듯한뎅 같이 해봅시닿

**Comment by k1rh4** [comment]
그림 이쁩니다 ㅋ 
1장에서 보라색이 빨간색에게 메시지를 주는것도 볼수없음으로 표시되는게좋을거같아요. 
지금은 보라색은 볼수있을것같은그림.

**Comment by k1rh4** [comment]
2장
Anonymizing msgs between clients with PGP keys 
between 은 둘사이의 관계라. among 으로 바꾸던가 between A and B 형식으로 바꿔야할거같아요.
발표는 문법도 보신다고했으니..
msg 도  msgs 라고 쓰니 뭔가 이상한 느낌이네요  messages 가 좋을거같아요.
can not see 에 띄어쓰기가 있어야할것 같아요.
Relaying msgs to others while decrypting. -> 복호화 한 뒤에 메지시가 아닐시 릴레이한다가 정확한 표현같아요. 복호화 하는 동안 보다.

**Comment by k1rh4** [comment]
3장. 
Possible security vulnerabilities 문구가 우리가 고려해서 막은건지, 아니면 가능할수도 있다는 것인지 좀 헤깔리는 듯..  -> Considering open vulnerabilities.  처럼 고려했다. 라는 식이 좋을것 같고,  먹힐 수 있는 공격 위헙이라면 빼도 좋을것 같아요. (단점을 굳이 언급할 필요없으니)
그리고 리스트에 command injection도 추가하면 좋을것같아요

**Comment by soohun-kim** [comment]
4장 --> SE 관점에서 필요할 것 같아서..
5장 --> MS SDL requirements phase에서 수행하는 task
7장 --> 메세지도 노드를 거쳐서 이동한다고 표현하고 싶으나 어떻게 해야할지 몰라서 일단 보류
9장 --> 역시 MS SDL에서 Design Phase에 요구하는 task DFD를 표현하고 싶었으나 일단 미완상태
10장 11장 --> 9장에서 표현한 DFD에서 Interaction의 주체가 다름
Implementation은 예를들어 PGPManager의 경우 Arguments 잘 만들어서 Popen호출 하는 식으로 수행하였다 + 정규표현식으로 Input sanitization 수행하였다 정도의 코드 설명?
Static analysis또한 MS SDL Implementation phase..
Test gogo~

---
 4, 5 장 접수완료~~
6장 서비스를 개발하기 앞서, 개발할 서비스에 존재할 수 있는 위협들? 을 미리 정의 해두고 관리하기 위한 목적..

**Comment by sunnyeo** [comment]
그럼 3장에서 onion messenger 설명한 다음에 우리는 ms sdl과정으로 개발을 했다
ms sdl 순서에 이렇고 이 순서에 따라 우리 프로그램 설계 과정을 설명하겠다 이런말들이 있어도 좋을듯요

**Comment by soohun-kim** [comment]
좋아요 말로하려했는데
넣어볼게요
어떻게 넣어야 할지 고민이되어서 일단 보류였음

**Comment by sunnyeo** [comment]
말로만 해도 될듯한뎅 차라리 목차자리에 onion messenger 설명을 넣구 그 다음에 sdl 과정을 목차처럼 넣어서 설명하는건 어떤가요

**Comment by soohun-kim** [comment]
좋아욥

**Comment by k1rh4** [comment]
이건 건의 메시지 전송할때마다 JSON 프로토콜이 어떻게 구성되나도 설명하면 좀더 좋치않을까?
{"sender:"1111","receiever":"2222","data":Enc({"sender:"2222","receiver:"3333","data":"aaaa"})    이런거
