### ISSUE TITLE
README draft version

### ISSUE THREAD

**Issue by soohun-kim** [KAIST-IS521/2018s-presentation-team6#6]
* Contents 
* Layout

[Suggested template](https://github.com/KAIST-IS521/2018s-pitch-activity/blob/master/PITCHME.md)

**Comment by sunnyeo** [comment]
README.md file that contains an abstract of your team introduction document. The abstract should concisely summarize your introduction document.

**Comment by sunnyeo** [comment]
team name, team member
abstract

**Comment by k1rh4** [comment]
리드미 abstract 와 설명 추가하여 넣었습니다
